"use strict";
exports.__esModule = true;
var shared_1 = require("@monorepo/shared");
var deep_1 = require("@monorepo/shared/deep");
// import { greetUserDeeply } from '@monorepo/shared/deep';
deep_1.greetUserDeeply;
var aws_cdk_lib_1 = require("aws-cdk-lib");
console.log(aws_cdk_lib_1.RemovalPolicy.RETAIN);
shared_1.greetUser('client');
deep_1.greetUserDeeply('client');
